  function normalizeDomainInput(v){let d=String(v||'').trim().toLowerCase();if(d.includes('://'))d=d.split('://')[1];d=d.split('/')[0];d=d.replace(/:\d+$/,'');if(d.startsWith('www.'))d=d.slice(4);return d}
  function slugifyName(str){return String(str||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)}
  function generateSecurePassword(){const up='ABCDEFGHJKLMNPQRSTUVWXYZ',lo='abcdefghijkmnpqrstuvwxyz',nm='23456789',sy='!@#$%&*+-=?_',all=up+lo+nm+sy;let p='';p+=up[Math.floor(Math.random()*up.length)];p+=lo[Math.floor(Math.random()*lo.length)];p+=nm[Math.floor(Math.random()*nm.length)];p+=sy[Math.floor(Math.random()*sy.length)];for(let i=0;i<8;i++)p+=all[Math.floor(Math.random()*all.length)];return p.split('').sort(()=>Math.random()-0.5).join('')}
  function copyText(text){const done=()=>toast('Copiado para a área de transferência.');if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(done).catch(()=>fallbackCopy(text))}else fallbackCopy(text)}
  function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');toast('Copiado para a área de transferência.')}catch(e){toast('Não foi possível copiar.')}document.body.removeChild(ta)}
  function validateTenantForm(fd,editing){const errors=[];if(!fd.name||String(fd.name).trim().length<2)errors.push({field:'name',msg:'Informe o nome da empresa.'});if(fd.slug&&!/^[a-z0-9-]+$/.test(fd.slug))errors.push({field:'slug',msg:'Slug inválido (use minúsculas, números e hífens).'});if(fd.domain){const nd=normalizeDomainInput(fd.domain);if(nd&&(!nd.includes('.')||/\s/.test(nd)))errors.push({field:'domain',msg:'Informe um domínio válido (ex: suasite.com.br).'})}if(!editing){if(!fd.adminName||String(fd.adminName).trim().length<2)errors.push({field:'adminName',msg:'Informe o nome do administrador.'});if(!fd.adminEmail)errors.push({field:'adminEmail',msg:'Informe o e-mail de acesso ao painel.'});else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fd.adminEmail))errors.push({field:'adminEmail',msg:'Informe um e-mail válido.'});if(!fd.adminPassword)errors.push({field:'adminPassword',msg:'Informe a senha inicial.'});else if(String(fd.adminPassword).length<8)errors.push({field:'adminPassword',msg:'A senha deve ter pelo menos 8 caracteres.'});if(!fd.confirmPassword)errors.push({field:'confirmPassword',msg:'Confirme a senha.'});else if(fd.adminPassword!==fd.confirmPassword)errors.push({field:'confirmPassword',msg:'As senhas não coincidem.'});const unitFields=[['unitName','nome'],['unitPhone','telefone'],['unitZipcode','CEP'],['unitStreet','rua'],['unitNumber','número'],['unitNeighborhood','bairro'],['unitCity','cidade'],['unitState','estado (UF)'],['unitCapacity','capacidade simultânea'],['unitOpeningTime','horário de abertura'],['unitClosingTime','horário de fechamento']];for(const [k,label] of unitFields){if(!fd[k]||!String(fd[k]).trim())errors.push({field:k,msg:'Informe '+label+' da unidade.'})}if(fd.unitPhone){const ph=String(fd.unitPhone).replace(/\D/g,'');if(ph.length<10||ph.length>13)errors.push({field:'unitPhone',msg:'Telefone da unidade inválido.'})}if(fd.unitZipcode){const zc=String(fd.unitZipcode).replace(/\D/g,'');if(zc.length!==8)errors.push({field:'unitZipcode',msg:'CEP inválido.'})}if(fd.unitState&&!/^[A-Za-z]{2}$/.test(String(fd.unitState).trim()))errors.push({field:'unitState',msg:'Estado inválido (use a sigla, ex: SP).'});if(fd.unitOpeningTime&&fd.unitClosingTime&&fd.unitClosingTime<=fd.unitOpeningTime)errors.push({field:'unitClosingTime',msg:'O horário de fechamento deve ser após a abertura.'});if(fd.unitCapacity!==''&&fd.unitCapacity!==undefined){const cap=Number(fd.unitCapacity);if(!Number.isInteger(cap)||cap<1||cap>20)errors.push({field:'unitCapacity',msg:'Capacidade deve ser entre 1 e 20.'})}if(!fd.unitWorkingDays||!fd.unitWorkingDays.length)errors.push({field:'unitWorkingDays',msg:'Selecione pelo menos um dia de funcionamento da unidade.'})}return errors}
  function showFormErrors(errors){document.querySelectorAll('#tenantForm .field-error').forEach(el=>el.classList.remove('field-error'));const box=$('#formErrors');if(!box)return;if(!errors.length){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<strong>Corrija os campos abaixo:</strong><ul>${errors.map(er=>`<li>${esc(er.msg)}</li>`).join('')}</ul>`;errors.forEach(er=>{const el=document.querySelector(`#tenantForm [name="${er.field}"]`);if(el)el.classList.add('field-error')})}
  function updateAccessPreview(){const input=$('#domainInput');const box=$('#accessPreview');if(!input||!box)return;const d=normalizeDomainInput(input.value);if(!d){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<div class="access-preview"><span>Acesso administrativo</span><code>https://${esc(d)}/admin</code></div>`}
  function showCreatedSuccess(created,fd){const domain=normalizeDomainInput(fd.domain||'');const accessUrl=domain?`https://${domain}/admin`:null;$('#modalBody').innerHTML=`<div class="success-card"><h2>Empresa criada com sucesso</h2><p class="muted">As credenciais abaixo são do painel administrativo da empresa.</p><div class="success-rows"><div><span>Empresa</span><b>${esc(created.name)}</b></div><div><span>Administrador</span><b>${esc(fd.adminName)}</b></div><div><span>Login</span><b>${esc(fd.adminEmail)}</b></div>${accessUrl?`<div><span>Acesso</span><b>${esc(accessUrl)}</b></div>`:''}${fd.adminPassword?`<div class="once"><span>Senha inicial</span><b class="one-time">${esc(fd.adminPassword)}</b><small class="warn">Guarde esta senha. Ela não poderá ser consultada novamente.</small></div>`:''}</div>${accessUrl?`<button type="button" class="primary" id="copyAccess">Copiar dados de acesso</button>`:''}<button type="button" id="successClose" class="ghost">Fechar</button></div>`;openModal();if(accessUrl&&$('#copyAccess'))$('#copyAccess').onclick=()=>copyText(`Empresa: ${created.name}\nAcesso: ${accessUrl}\nLogin: ${fd.adminEmail}`);$('#successClose').onclick=()=>{$('#modal').close();render()}}
  function renderOwnerSection(tenant,owner){const box=$('#ownerSection');if(!box)return;if(!owner){box.innerHTML=`<p class="muted">Nenhum administrador vinculado a esta empresa.</p>`;return}box.innerHTML=`<div class="owner-card"><div class="owner-grid"><div><span>Nome</span><b>${esc(owner.name)}</b></div><div><span>E-mail de acesso</span><b>${esc(owner.email)}</b></div><div><span>Perfil</span><b>${esc(roleLabel(owner.role))}</b></div><div><span>Status</span><b class="${owner.active?'ok':'bad'}">${owner.active?'Ativo':'Inativo'}</b></div></div><div class="actions owner-actions"><button type="button" data-owner-action="edit-name">Editar nome</button><button type="button" data-owner-action="edit-email">Editar e-mail</button><button type="button" data-owner-action="reset-pass">Redefinir senha</button><button type="button" data-owner-action="toggle-active" class="${owner.active?'danger':''}">${owner.active?'Desativar':'Ativar'}</button></div></div>`;box.onclick=async e=>{const b=e.target.closest('[data-owner-action]');if(!b)return;if(b.dataset.ownerAction==='toggle-active'){if(!confirm(`${owner.active?'Desativar':'Ativar'} o administrador "${owner.email}"?`))return;try{await api(`/api/developer/tenants/${tenant.id}/owner`,{method:'PATCH',body:JSON.stringify({active:owner.active?0:1})});toast('Status do administrador atualizado.');loadTenantUsers(tenant)}catch(err){toast(err.message)}return}showOwnerMiniForm(tenant,owner,b.dataset.ownerAction)}}
  function showOwnerMiniForm(tenant,owner,action){const box=$('#ownerSection');if(!box)return;let body='';if(action==='name'){body=`<div class="owner-card"><h4>Editar nome do administrador</h4><form id="ownerMiniForm" class="grid-form"><label>Nome do administrador<input name="ownerName" value="${esc(owner.name)}" required></label><div class="actions wide"><button type="button" data-cancel-owner>Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>`}else if(action==='email'){body=`<div class="owner-card"><h4>Editar e-mail de acesso</h4><p class="muted wide">Novo login para acessar /admin no domínio da empresa.</p><form id="ownerMiniForm" class="grid-form"><label>E-mail de acesso ao painel<input name="ownerEmail" type="email" value="${esc(owner.email)}" required></label><div class="actions wide"><button type="button" data-cancel-owner>Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>`}else{body=`<div class="owner-card"><h4>Redefinir senha</h4><form id="ownerMiniForm" class="grid-form"><label>Nova senha<input name="new_password" type="password" minlength="8" required placeholder="Mínimo de 8 caracteres" autocomplete="new-password"></label><label>Confirmar nova senha<input name="confirm_password" type="password" minlength="8" required placeholder="Repita a senha" autocomplete="new-password"></label><div class="actions wide"><button type="button" data-cancel-owner>Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>`}box.innerHTML=body;box.querySelector('[data-cancel-owner]').onclick=()=>loadTenantUsers(tenant);$('#ownerMiniForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{if(action==='name'){const name=$('#ownerMiniForm [name="ownerName"]').value;if(!name||name.trim().length<2)throw new Error('Informe o nome do administrador.');await api(`/api/developer/tenants/${tenant.id}/owner`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});toast('Nome do administrador atualizado.')}else if(action==='email'){const em=$('#ownerMiniForm [name="ownerEmail"]').value;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em))throw new Error('Informe um e-mail válido.');await api(`/api/developer/tenants/${tenant.id}/owner`,{method:'PATCH',body:JSON.stringify({email:em})});toast('E-mail de acesso atualizado.')}else{const p=$('#ownerMiniForm [name="new_password"]').value,c=$('#ownerMiniForm [name="confirm_password"]').value;if(!p||p.length<8)throw new Error('A nova senha deve ter pelo menos 8 caracteres.');if(p!==c)throw new Error('As senhas não coincidem.');await api(`/api/developer/tenants/${tenant.id}/reset-password`,{method:'POST',body:JSON.stringify({new_password:p,confirm_password:c})});toast('Senha redefinida.')}loadTenantUsers(tenant)}catch(err){toast(err.message)}finally{btn.disabled=false}}}
  function openTenantForm(tenant){const editing=Boolean(tenant);const opts=state.plans.map(p=>`<option value="${esc(p.slug)}" ${editing&&tenant.plan===p.slug?'selected':''}>${esc(p.name)}</option>`).join('');const statusList=editing?['ACTIVE','TRIAL','SUSPENDED','ARCHIVED']:['ACTIVE','TRIAL','SUSPENDED'];const statusOpts=statusList.map(s=>`<option ${editing&&tenant.status===s?'selected':''}>${s}</option>`).join('');const primaryDomainObj=editing?tenant.domains?.find(d=>d.is_primary):null;const extraDomains=editing?(tenant.domains?.length||0)-(primaryDomainObj?1:0):0;const companySection=`
      <div class="form-section wide">
        <h3>Dados da empresa</h3>
        <div class="grid-form">
          <label>Nome da empresa *<input name="name" id="tenantName" value="${editing?esc(tenant.name):''}" required></label>
          <label>Slug<input name="slug" id="tenantSlug" pattern="[a-z0-9\\-]+" value="${editing?esc(tenant.slug):''}" placeholder="Gerado do nome"></label>
          <label>Plano *<select name="plan">${opts}</select></label>
          <label>Status *<select name="status">${statusOpts}</select></label>
          <label>Documento (CNPJ/CPF)<input name="document" value="${editing?esc(tenant.document||''):''}"></label>
          <label>E-mail comercial da empresa<input name="email" type="email" value="${editing?esc(tenant.email||''):''}" placeholder="Não usado como login"></label>
          <label>Telefone<input name="phone" value="${editing?esc(tenant.phone||''):''}"></label>
          <label>Domínio principal<input name="domain" id="domainInput" value="${editing?esc(primaryDomainObj?.domain||''):''}" placeholder="suasite.com.br"></label>
          <label>Vencimento<input name="expires_at" type="date" value="${editing&&tenant.expires_at?tenant.expires_at:''}"></label>
        </div>
        <div id="accessPreview" class="access-preview-wrap hidden"></div>
        ${editing&&extraDomains>0?`<p class="muted wide">Esta empresa também tem ${extraDomains} domínio(s) secundário(s) — gerencie na aba "Domínios".</p>`:''}
      </div>`;const adminSection=editing?'':`
      <div class="form-section wide">
        <h3>Administrador da empresa</h3>
        <p class="muted wide">Estas credenciais serão usadas pelo cliente para acessar <code>/admin</code> no domínio da empresa. O usuário administra somente esta empresa.</p>
        <div class="grid-form">
          <label>Nome do administrador *<input name="adminName" required></label>
          <label>E-mail de acesso ao painel *<input name="adminEmail" type="email" required><small class="help">Este será o login usado para acessar /admin no domínio da empresa.</small></label>
          <label>Senha inicial *<span class="password"><input name="adminPassword" id="adminPassword" type="password" minlength="8" required autocomplete="new-password"><button type="button" id="togglePassword1">Mostrar</button></span><small class="help">O administrador usará esta senha no primeiro acesso. Mínimo de 8 caracteres.</small></label>
          <label>Confirmar senha *<span class="password"><input name="confirmPassword" id="confirmPassword" type="password" minlength="8" required autocomplete="new-password"><button type="button" id="togglePassword2">Mostrar</button></span></label>
        </div>
        <div class="password-tools wide">
          <button type="button" id="genPassword" class="ghost">Gerar senha segura</button>
          <button type="button" id="copyPassword" class="ghost">Copiar senha</button>
        </div>
      </div>`;const dayNames=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];const unitSection=!editing?`
      <div class="form-section wide">
        <h3>Primeira unidade</h3>
        <p class="muted wide">Estes dados são salvos na implantação e ficam visíveis na agenda e no site público da empresa. Campos com * são obrigatórios.</p>
        <div class="grid-form">
          <label>Nome da unidade *<input name="unitName" required placeholder="Ex: Matriz"></label>
          <label>Telefone *<input name="unitPhone" inputmode="tel" required placeholder="(11) 99999-9999"></label>
          <label>CEP *<input name="unitZipcode" inputmode="numeric" maxlength="9" required placeholder="00000-000"></label>
          <label>Rua *<input name="unitStreet" required></label>
          <label>Número *<input name="unitNumber" required></label>
          <label>Complemento<input name="unitComplement"></label>
          <label>Bairro *<input name="unitNeighborhood" required></label>
          <label>Cidade *<input name="unitCity" required></label>
          <label>Estado (UF) *<input name="unitState" maxlength="2" required placeholder="SP"></label>
          <label>Capacidade simultânea *<input name="unitCapacity" type="number" min="1" max="20" value="1" required></label>
          <label>Abertura *<input name="unitOpeningTime" type="time" value="08:00" required></label>
          <label>Fechamento *<input name="unitClosingTime" type="time" value="17:00" required></label>
          <label>Intervalo entre agendamentos<select name="unitInterval"><option value="30">30 minutos</option><option value="60" selected>60 minutos</option><option value="90">90 minutos</option><option value="120">2 horas</option></select></label>
          <label>Ponto de referência<input name="unitReference"></label>
          <label>Link do Google Maps<input name="unitMapsLink" placeholder="https://maps.app.goo.gl/..."></label>
        </div>
        <div class="wide" style="margin-top:8px"><span class="field-label">Dias de funcionamento *</span><div class="day-chips">${dayNames.map((label,i)=>`<label class="day-chip"><input type="checkbox" name="unitWorkingDays" value="${i}" ${[1,2,3,4,5,6].includes(i)?'checked':''}>${label}</label>`).join('')}</div></div>
      </div>`:'';const ownerSection=editing?`
      <div class="form-section wide">
        <h3>Administrador principal</h3>
        <div id="ownerSection" class="muted">Carregando…</div>
      </div>
      <div class="section-head"><h3>Usuários da empresa</h3><button type="button" id="addTenantUser" class="primary">+ Novo usuário</button></div>
      <div id="tenantUsersList" class="muted">Carregando…</div>
      <div class="section-head"><h3>Identidade Visual</h3><p class="muted">Logo e favicon exibidos no site público e no painel da empresa.</p></div>
      <div id="brandingBox" class="wide muted">Carregando…</div>`:'';$('#modalBody').innerHTML=`<h2>${editing?'Editar empresa':'Nova empresa'}</h2><form id="tenantForm" class="grid-form" novalidate>${companySection}${adminSection}${unitSection}<div id="formErrors" class="form-errors wide hidden"></div><div class="actions wide"><button type="button" data-close>Cancelar</button><button class="primary" type="submit">${editing?'Salvar alterações':'Criar empresa'}</button></div></form>${ownerSection}`;openModal();$('#tenantForm').querySelector('[data-close]').onclick=()=>$('#modal').close();$('#domainInput').oninput=updateAccessPreview;updateAccessPreview();if(!editing){const nameInput=$('#tenantName'),slugInput=$('#tenantSlug');nameInput.oninput=()=>{if(slugInput.dataset.manual!=='1')slugInput.value=slugifyName(nameInput.value)};slugInput.oninput=()=>{slugInput.dataset.manual='1'}}if(!editing){$('#genPassword').onclick=()=>{const p=generateSecurePassword();$('#adminPassword').value=p;$('#confirmPassword').value=p;toast('Senha segura gerada.')};$('#copyPassword').onclick=()=>{const p=$('#adminPassword').value;if(!p)return toast('Gere uma senha primeiro.');copyText(p)};$('#togglePassword1').onclick=()=>{const p=$('#adminPassword');p.type=p.type==='password'?'text':'password';$('#togglePassword1').textContent=p.type==='password'?'Mostrar':'Ocultar'};$('#togglePassword2').onclick=()=>{const p=$('#confirmPassword');p.type=p.type==='password'?'text':'password';$('#togglePassword2').textContent=p.type==='password'?'Mostrar':'Ocultar'}}let submitting=false;$('#tenantForm').onsubmit=async e=>{e.preventDefault();if(submitting)return;submitting=true;const btn=e.submitter;btn.disabled=true;const fd=Object.fromEntries(new FormData(e.target));fd.unitWorkingDays=[...e.target.querySelectorAll('[name="unitWorkingDays"]:checked')].map(c=>c.value);const errors=validateTenantForm(fd,editing);showFormErrors(errors);if(errors.length){submitting=false;btn.disabled=false;return}fd.domain=normalizeDomainInput(fd.domain||'');try{if(editing){await api(`/api/developer/tenants/${tenant.id}`,{method:'PUT',body:JSON.stringify(fd)});if(fd.domain&&fd.domain!==(primaryDomainObj?.domain||'')){try{if(primaryDomainObj)await api(`/api/developer/domains/${primaryDomainObj.id}`,{method:'PATCH',body:JSON.stringify({domain:fd.domain})});else await api(`/api/developer/tenants/${tenant.id}/domains`,{method:'POST',body:JSON.stringify({domain:fd.domain,is_primary:true})})}catch(domErr){toast(`Empresa atualizada, mas o domínio não foi salvo: ${domErr.message}`);$('#modal').close();render();return}}$('#modal').close();toast('Empresa atualizada.');render()}else{const created=await api('/api/developer/tenants',{method:'POST',body:JSON.stringify(fd)});showCreatedSuccess(created,fd)}}catch(err){toast(err.message)}finally{submitting=false;if(btn)btn.disabled=false}};if(editing){loadTenantUsers(tenant);$('#addTenantUser').onclick=()=>openTenantUserForm(tenant);loadBranding(tenant.id)}}
